import 'package:floor/floor.dart';
import 'package:group28/database/entities/sedentary.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Pace {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The carbohydrates content of the goal
  final double steptodo;

  //When the goal occured
  final DateTime dateTime;

  //Default constructor
  Pace(this.id, this.steptodo, this.dateTime);
}//Pace